// ------------------------------------------------------------------------------
//      This code was generated by handlebars/grunt.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// ------------------------------------------------------------------------------

var controls = require('./../../controls/controls.js');
var utilities = require('./../../utils/utilities.js');
var pagedata = utilities.readJsonFile(__dirname + '/EstimateMonthlyPaymentPage.json');

function EstimateMonthlyPaymentPage(){
      this.pageUrl = '/pub/w/estimate-payment/1';
      this.ZipCodeTextBox = new controls.TextBox(pagedata.Controls.ZipCode.SelectType, pagedata.Controls.ZipCode.Selector);
      this.StartBtnButton = new controls.Button(pagedata.Controls.StartBtn.SelectType, pagedata.Controls.StartBtn.Selector);
      this.Group_HYBRIDLabel = new controls.Label(pagedata.Controls.Group_HYBRID.SelectType, pagedata.Controls.Group_HYBRID.Selector);
      this.RX_HYBRIDLink = new controls.Link(pagedata.Controls.RX_HYBRID.SelectType, pagedata.Controls.RX_HYBRID.Selector);
};

module.exports = EstimateMonthlyPaymentPage;
