// ------------------------------------------------------------------------------
//      This code was generated by handlebars/grunt.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// ------------------------------------------------------------------------------

var controls = require('./../../controls/controls.js');
var utilities = require('./../../utils/utilities.js');
var pagedata = utilities.readJsonFile(__dirname + '/HomePage.json');

function HomePage(){
      this.pageUrl = '/pub/w';
      this.FinancialToolsButton = new controls.Button(pagedata.Controls.FinancialTools.SelectType, pagedata.Controls.FinancialTools.Selector);
      this.EstimateMonthlyPaymentLink = new controls.Link(pagedata.Controls.EstimateMonthlyPayment.SelectType, pagedata.Controls.EstimateMonthlyPayment.Selector);
};

module.exports = HomePage;
