// ------------------------------------------------------------------------------
//      This code was generated by handlebars/grunt.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// ------------------------------------------------------------------------------

var controls = require('./../controls/controls.js');
var utilities = require('./../utils/utilities.js');
var pagedata = utilities.readJsonFile(__dirname + '/../pages/BuyPage.json');

function BuyPage(){
      this.pageUrl = '/pub/w/payment_estimator/get_payment/buy';
      this.RecalculateButton = new controls.Button(pagedata.Controls.Recalculate.SelectType, pagedata.Controls.Recalculate.Selector);
};

module.exports = BuyPage;
