// ------------------------------------------------------------------------------
//      This code was generated by handlebars/grunt.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// ------------------------------------------------------------------------------

var controls = require('./../controls/controls.js');
var utilities = require('./../utils/utilities.js');
var pagedata = utilities.readJsonFile(__dirname + '/../pages/EstimateMonthlyPaymentPage.json');

function EstimateMonthlyPaymentPage(){
      this.pageUrl = '/pub/w/payment_estimator';
      this.ZipCodeTextBox = new controls.TextBox(pagedata.Controls.ZipCode.SelectType, pagedata.Controls.ZipCode.Selector);
      this.RX_HYBRIDButton = new controls.Button(pagedata.Controls.RX_HYBRID.SelectType, pagedata.Controls.RX_HYBRID.Selector);
};

module.exports = EstimateMonthlyPaymentPage;
