// ------------------------------------------------------------------------------
//      This code was generated by handlebars/grunt.
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// ------------------------------------------------------------------------------

var controls = require('./../controls/controls.js');
var utilities = require('./../utils/utilities.js');
var pagedata = utilities.readJsonFile(__dirname + '/../pages/SelectTrimPage.json');

function SelectTrimPage(){
      this.pageUrl = '/pub/w/estimate-payment/2';
      this.TrimLink = new controls.Link(pagedata.Controls.Trim.SelectType, pagedata.Controls.Trim.Selector);
      this.NavbarToggleButton = new controls.Button(pagedata.Controls.NavbarToggle.SelectType, pagedata.Controls.NavbarToggle.Selector);
      this.MenuLargePaymentEstimatorButton = new controls.Button(pagedata.Controls.MenuLargePaymentEstimator.SelectType, pagedata.Controls.MenuLargePaymentEstimator.Selector);
      this.MenuSmallPaymentEstimatorButton = new controls.Button(pagedata.Controls.MenuSmallPaymentEstimator.SelectType, pagedata.Controls.MenuSmallPaymentEstimator.Selector);
      this.LoadingLabel = new controls.Label(pagedata.Controls.Loading.SelectType, pagedata.Controls.Loading.Selector);
};

module.exports = SelectTrimPage;
